//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR30
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public int SellerId { get; set; }
        public int CategoryId { get; set; }
        public string PublicationName { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public string ProductCondition { get; set; }
        public string Description { get; set; }
        public string PaymentMethod { get; set; }
        public string DeliveryMethod { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Sellers Sellers { get; set; }
    }
}
